### ISSUE TITLE
Allow formatting to output values with lengths of 8 characters or more

### ISSUE THREAD

**Issue by cbanksbi** [rpander93/react-native-animated-number#7]
Right now I'm running into a scenario where I have a formatter that will convert my numeric values into currency. In the case of USD, when the value exceeds a length of 7 characters my output is clipped. Example:

`$15,000.00 => $15,000.0` or `$114,999.99 => $114,999.`

Is there a pre-existing way to prevent this from occurring? My current formatter is setup as follows:

```
const toCurrency = (value, currency = 'USD') => {
  return (Math.ceil(value * 100) / 10000).toLocaleString('en-US', { minimumFractionDigits: 2, style: 'currency', currency: currency });
};
```

**Comment by rpander93** [comment]
Hi @cbanksbi, after running the component with your example I removed the Math.ceil() call from it and then it ran fine. The component's code doesnt contain any code that would clip the value to 7 characters length. Am I missing something?

**Comment by cbanksbi** [comment]
Mistake on my part. Sorry for the confusion.
